### ISSUE TITLE
Auto Stop idle script giving error

### ISSUE THREAD

**Issue by ambrish** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#75] opened 2021-12-21 10:57 UTC
Hi,

I have tried using this stop auto idle however following all the steps its giving me error as below 

Error:
/bin/bash^M: bad interpreter: No such file or directory
/bin/bash: /tmp/OnStart_2021-12-21-07-55j53iytbj: /bin/bash^M: bad interpreter: No such file or directory

even after removing /bin/bash it gives other error 

<html>
<body>

/tmp/OnStart_2021-12-21-08-36jg8sy0tu: line 1: set: -: invalid option
--
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
/tmp/OnStart_2021-12-21-08-36jg8sy0tu: line 2: 
</body>
</html>\r': command not found
/tmp/OnStart_2021-12-21-08-36jg8sy0tu: line 13: 
</body>
</html>\r': command not found
/tmp/OnStart_2021-12-21-08-36jg8sy0tu: line 16: 
</body>
</html>\r': command not found
Fetching the autostop script
--2021-12-21 08:36:11--  https://raw.githubusercontent.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/master/scripts/auto-stop-idle/autostop.py%0D
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)\|185.199.109.133\|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-12-21 08:36:11 ERROR 404: Not Found.
/tmp/OnStart_2021-12-21-08-36jg8sy0tu: line 19: 
</body>
</html>\r': command not found
Starting the SageMaker autostop script in cron
/tmp/OnStart_2021-12-21-08-36jg8sy0tu: line 21: 
</body>
</html>\r': command not found

</body>
</html>

**Comment by rmamone-reply** [comment] 2024-02-26 12:20
I'm also having this issue. Does anyone have a solution?

**Comment by rmamone-reply** [comment] 2024-02-26 13:14
For anyone facing this issue, the problem is caused by wrong end of line sequence character, pasting the script in windows changes LF character with CRLF character, which is not ok for Linux machines.

**Comment by dmlause** [comment] 2024-03-01 20:06
Closing this issue for now given the response from @rmamone-reply above. Please reopen the issue if there is still a problem that needs to be addressed. Thank you.

**Closed by dmlause** 2024-03-01 20:06 UTC
