### ISSUE TITLE
Updated autostop script not working

### ISSUE THREAD

**Issue by nethraui** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#100] opened 2022-11-05 23:03 UTC
Auto-stop cronjob not working since the last update on autostop script.

**Comment by dylonbotha** [comment] 2022-11-07 12:09
Any updates on this issue. It seems to be a syntax error related to the most recent PR completed to master

![image](https://user-images.githubusercontent.com/117648658/200306780-daffe097-e355-4207-8790-56a59e9de497.png)

**Comment by Pete-rePete** [comment] 2022-11-21 13:56
To summarize the likely root cause: 
Many Sagemaker notebook instances run `autostop.py` using the default system python2.7, and these fstrings broke autostop. [A fix has already been merged](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/commit/13b4023c9dca45fea58b2129fe5848619284653a). Tagging @tayodok to confirm

**Comment by dmlause** [comment] 2024-03-05 20:53
Closing this issue as the fix above has been merged already. Please open a new issue if something different comes up, thank you.

**Closed by dmlause** 2024-03-05 20:53 UTC
